run:
  timeout: 5m

linters:
  enable:
    - govet
    - staticcheck
    - errcheck
    - ineffassign
    - typecheck
    - unused

issues:
  exclude-use-default: false

linters-settings:
  errcheck:
    exclude-functions:
      - (*bytes.Buffer).Write
      - (*bytes.Buffer).WriteString
      - (*bytes.Buffer).Read
      - (io.Writer).Write
      - (io.Reader).Read
